### PR TITLE
Assignment1 yanguo xu

### PR DESCRIPTION
**Pull request by stephen30ppp**
**Addressed Issue**
The issue addressed was the lack of modularity and excessive complexity in the main application code (app.R or potentially combined code in ui.R and server.R), which resulted in a tightly coupled structure. This setup increased maintenance difficulties, reduced code readability, and hindered efficient debugging and scalability.

**What You Have Reengineered**
I have refactored the code by modularizing functions and optimizing redundant code blocks. This entailed breaking down the main app.R into separate, reusable modules for different UI components and server functions. Additionally, any repetitive code sections were consolidated into utility functions, making the codebase more efficient and manageable.

**Reengineering Strategy or Approach Used**
The reengineering strategy used focused on:

- Modularization: By isolating each functional part of the app into modules, the app now has a better separation of concerns, where each module handles a distinct task.

- Code Refactoring and Optimization: Reorganized and simplified existing code blocks for efficiency. Functions were identified and separated where redundancy was found, and these were moved to helper files to reduce repetition and improve performance.

- Performance Enhancements: Memory and performance bottlenecks were addressed by optimizing loops, cleaning up unnecessary variables, and minimizing reactive expressions that were needlessly complex or duplicated.

**Impact of Changes**
The code optimization has yielded several improvements:

- Enhanced Readability and Maintainability:New contributors or maintainers can now more easily understand and work with the code due to its organized modular structure.

- Scalability: The modular approach allows for future features or updates to be integrated seamlessly without disrupting the core code.

- Improved Performance: Optimizations have reduced the memory footprint and load time, resulting in faster user interactions and a more responsive UI.

- Easier Debugging and Testing: With a well-organized codebase, unit tests can be more easily developed for each module, improving the app's reliability and reducing the likelihood of bugs.

**This structured approach provides a clear description of the code optimization task, outlining the original issue, the steps taken to address it, the strategies used, and the tangible impact on the application**

### CODE REVIEW

**Comment by stephen30ppp** [comment]
. @suhadaudd11

> **Addressed Issue** The issue addressed was the lack of modularity and excessive complexity in the main application code (app.R or potentially combined code in ui.R and server.R), which resulted in a tightly coupled structure. This setup increased maintenance difficulties, reduced code readability, and hindered efficient debugging and scalability.
> 
> **What You Have Reengineered** I have refactored the code by modularizing functions and optimizing redundant code blocks. This entailed breaking down the main app.R into separate, reusable modules for different UI components and server functions. Additionally, any repetitive code sections were consolidated into utility functions, making the codebase more efficient and manageable.
> 
> **Reengineering Strategy or Approach Used** The reengineering strategy used focused on:
> 
> * Modularization: By isolating each functional part of the app into modules, the app now has a better separation of concerns, where each module handles a distinct task.
> * Code Refactoring and Optimization: Reorganized and simplified existing code blocks for efficiency. Functions were identified and separated where redundancy was found, and these were moved to helper files to reduce repetition and improve performance.
> * Performance Enhancements: Memory and performance bottlenecks were addressed by optimizing loops, cleaning up unnecessary variables, and minimizing reactive expressions that were needlessly complex or duplicated.
> 
> **Impact of Changes** The code optimization has yielded several improvements:
> 
> * Enhanced Readability and Maintainability:New contributors or maintainers can now more easily understand and work with the code due to its organized modular structure.
> * Scalability: The modular approach allows for future features or updates to be integrated seamlessly without disrupting the core code.
> * Improved Performance: Optimizations have reduced the memory footprint and load time, resulting in faster user interactions and a more responsive UI.
> * Easier Debugging and Testing: With a well-organized codebase, unit tests can be more easily developed for each module, improving the app's reliability and reducing the likelihood of bugs.
> 
> **This structured approach provides a clear description of the code optimization task, outlining the original issue, the steps taken to address it, the strategies used, and the tangible impact on the application**

**Review by stephen30ppp — COMMENTED** [review]
@suhadaudd11

**Review by stephen30ppp — COMMENTED** [review]
@suhadaudd11

**Review by stephen30ppp — COMMENTED** [review]
@suhadaudd11

**Comment by delosh653** [comment]
This PR is clearly for an assignment unrelated to this project. Further, these changes were not requested/brought up in an issue and do not follow the style of the repository, and cannot be implemented for the project. In the future, please suggest fixes via issue tickets so that we can understand and guide requests before substantial work is done. Thank you, I will close this request.

**Pull request closed without merging**
